server {
    listen 80;
    server_name tico.kro.kr 43.202.174.19;

    # HTTP로 들어온 요청을 HTTPS로 리다이렉트
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tico.kro.kr 43.202.174.19;

    # 실제 파일명, 경로에 맞게 수정!
    ssl_certificate     /etc/ssl/certs/ca_bundle.crt;         # 인증서 파일
    ssl_certificate_key /etc/ssl/private/private.key;      # 개인키
    ssl_trusted_certificate /etc/ssl/certs/certificate.crt;       # 체인(있으면)

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
