version: '3'
services:
  react:
    build: ./front-react
    image: tico-react
    ports:
      - "80:80"

  flask:
    build: ./python
    image: tico-python
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/my-project-tico-d3f43b48a318.json
      - DB_PORT=3306
    volumes:
      # env 파일을 도커 컨테이너에서 인식하기 위해서 설정한다./app은 Dockerfile의 WORKDIR와 일치해야 함
      - ./python/chatbot/.env:/app/.env  
      - ./python/my-project-tico-d3f43b48a318.json:/app/my-project-tico-d3f43b48a318.json

  spring:
    build:
      context: .
      dockerfile: ./Dockerfile.spring
    image: tico-spring-boot
    ports:
      - "8081:8081"
    volumes:
      - /home/ec2-user/TICO_TEAM/uploads:/uploads
