services:
  # ------------------------
  # 1) React 컨테이너(Nginx + 정적파일 서빙)
  react:
    build: ./front-react
    image: tico-react
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # front-react 폴더 안에 있는 nginx.conf 를 컨테이너 default.conf 로 덮어씌웁니다.
      - ./front-react/nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # SSL 인증서 체인, 최상위 인증서, 개인키
      - ./ssl/certificate.crt:/etc/ssl/certs/certificate.crt:ro
      - ./ssl/private.key:/etc/ssl/private/private.key:ro

      # 빌드된 정적 파일
      # ./front-react/build:/usr/share/nginx/html:ro

      # 도커에서 빌드시 필요한 env -> 로컬에서 빌드시 해당 코드 필요없음
      # - ./front-react/.env:/app/.env  

  # ------------------------
  # 3) Flask
  flask:
    build: ./python
    image: tico-python
    expose:
      - "5000"  # 내부망에서만 접근 가능
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/my-project-tico-d3f43b48a318.json
      - DB_PORT=3306
    volumes:
      - ./python/chatbot/.env:/app/.env  
      - ./python/chatbot/my-project-tico-d3f43b48a318.json:/app/my-project-tico-d3f43b48a318.json
      - ./python/chatbot/static/audio_files:/app/chatbot/static/audio_files

  # ------------------------
  # 4) Spring Boot
  spring:
    build:
      context: .
      dockerfile: ./Dockerfile.spring
    image: tico-spring-boot
    ports:
      - "8081:8081"
    volumes:
      - /home/ec2-user/TICO_TEAM/uploads:/uploads
